# Generated by Django 5.0.6 on 2024-07-17 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='year',
            field=models.CharField(choices=[('KG1', 'KG1'), ('KG2', 'KG2')], default=1, max_length=10),
            preserve_default=False,
        ),
    ]
