# Generated by Django 5.0.6 on 2024-07-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homework', '0002_homework_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='homework_images/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='homework_images/'),
        ),
        migrations.AddField(
            model_name='homework',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='homework_images/'),
        ),
    ]
