# Generated by Django 5.0.6 on 2024-07-02 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitors',
            name='Ranking',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='competitors',
            name='score',
            field=models.IntegerField(),
        ),
    ]
