# Generated by Django 5.0.6 on 2024-07-02 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0002_alter_competitors_ranking_alter_competitors_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitors',
            name='the_game',
            field=models.CharField(choices=[('Memory game', 'Memory game')], default='Memory game', max_length=100),
        ),
    ]
