# Generated by Django 5.0.6 on 2024-07-11 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('competitions', '0003_competitors_the_game'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='competitors',
            name='Ranking',
        ),
        migrations.RemoveField(
            model_name='competitors',
            name='the_game',
        ),
    ]
